# Generated by Django 6.0.2 on 2026-02-11 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_name', models.CharField(max_length=150)),
                ('t_number', models.IntegerField()),
                ('t_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
